#! /bin/sh
dir="/Users/sts/Quellen/mac/hbci/lib/static-build-ppc-4.99.7beta"
# $Id$
# Author of this file: Martin Preuss<martin@libchipcard.de>

prefix=/Users/sts/Quellen/mac/hbci/lib/static-build-ppc-4.99.7beta
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
datarootdir=${prefix}/share
includedir=${prefix}/include
datadir=${datarootdir}

result=""

for d in $*; do
    case $d in
	--includes)
	    result="$result -I${includedir}/aqbanking5 -I/Users/sts/Quellen/mac/hbci/lib/static-build-ppc-4.99.7beta/include/gwenhywfar4"
	    ;;
	--libraries)
	    result="$result -L${libdir} -laqbanking"
	    ;;
	--libraries++)
	    result="$result "
	    ;;
	--plugins)
	    result="$result ${libdir}/aqbanking/plugins/32"
	    ;;
	--data)
	    result="$result ${datadir}/aqbanking"
	    ;;

        --has-qbanking)
            result=no
            ;;
	--qbanking-libraries)
	    result="$result -L${libdir} -L${libdir} -lqbanking"
	    ;;
	--qbanking-plugins)
	    result="$result ${aqbanking_plugindir}/frontends/qbanking"
	    ;;
	--qbanking-helpdir)
	    result="$result ${datadir}/aqbanking/frontends/qbanking/help"
	    ;;

        --has-aqhbci)
            result=yes
            ;;
	--aqhbci-libraries)
	    result="$result -L${libdir} -laqhbci"
	    ;;

	--vmajor)
	    result="$result 4"
	    ;;
	--vminor)
	    result="$result 99"
	    ;;
	--vpatchlevel)
	    result="$result 7"
	    ;;
	--vbuild)
	    result="$result 0"
	    ;;
	--vtag)
	    result="$result beta"
	    ;;
        --vstring)
	    result="$result 4.99.7"
            ;;
	*)
	    echo "Usage:"
	    echo "$0 --includes gives you the include flags"
	    echo "$0 --libraries gives you the library flags"
	    echo "$0 --vmajor gives the major version of AqBanking"
	    echo "$0 --vminor gives the minor version of AqBanking"
	    echo "$0 --vpatchlevel gives the patchlevel of AqBanking"
	    echo "$0 --vbuild gives the build number of AqBanking"
	    echo "$0 --vtag gives the tag of AqBanking (cvs, beta or stable)"
	    echo "$0 --vstring returns a version string"
	    exit 1
	    ;;
    esac
done
echo $result
