#!/bin/sh

# Copyright (C) 2007  Free Software Foundation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

# Sets up the execution environment needed to run the test programs
# and produce the documentation.


GUILE_LOAD_PATH="/Users/sts/Quellen/mac/hbci/lib/gnutls-2.8.5/guile/modules:$GUILE_LOAD_PATH"
export GUILE_LOAD_PATH

exec /Users/sts/Quellen/mac/hbci/lib/tmp-debug/gnutls-2.8.5/libtool --mode=execute		                    \
       -dlopen "/Users/sts/Quellen/mac/hbci/lib/tmp-debug/gnutls-2.8.5/guile/src/libguile-gnutls-v-1.la"        \
       -dlopen "/Users/sts/Quellen/mac/hbci/lib/tmp-debug/gnutls-2.8.5/guile/src/libguile-gnutls-extra-v-1.la"  \
        "$@"
