/**********************************************************
 * This file has been automatically created by "typemaker2"
 * from the file "/Users/michael/src/git/lib/aqbanking/src/libs/aqbanking/backendsupport/ab_accountqueue.xml".
 * Please do not edit this file, all changes will be lost.
 * Better edit the mentioned source file instead.
 **********************************************************/

#ifndef AB_ACCOUNTQUEUE_P_H
#define AB_ACCOUNTQUEUE_P_H

#include "ab_accountqueue.h"


#ifdef __cplusplus
extern "C" {
#endif

struct AB_ACCOUNTQUEUE {
  GWEN_INHERIT_ELEMENT(AB_ACCOUNTQUEUE)
  GWEN_LIST_ELEMENT(AB_ACCOUNTQUEUE)
  int _refCount;
  AB_ACCOUNT *account; /* volatile */
  AB_JOBQUEUE_LIST *jobQueueList; /* volatile */
};

#ifdef __cplusplus
}
#endif

#endif

